### ISSUE TITLE
Method with lambda expression can not be converted to jimple

### ISSUE THREAD

**Issue by sdibernardo** [Sable/soot#1146]
Hi, 

Im currently using Soot to analyze dataflow anomalies and need to visit classes and certain methods that reside in them. A current test case uses a lamdba expression inside a given method (see snippet below).

After retrieving the class (forceResolve works like a charm here), I iterate over the methods and try to get the method body by using "retrieveActiveBody". I dont know exactly what happens next, but while trying to retrieve the method body, Soot creates the LamdbaMetaFactory which provides a new wrapper and crashes (see [constructor](https://github.com/Sable/soot/blob/d3cff8d7dc46988570533dbf5e781eb2d115ffd2/src/main/java/soot/LambdaMetaFactory.java#L284) of the wrapper).

```
String valueOfMethodSignature = cn + " valueOf(" + primType.toString() + ")";
SootMethod valueOfMethod = wrapperType.getSootClass().getMethod(valueOfMethodSignature);
```
`cn` contains the value "java.lang.Boolean", `valueOfMethodSignature` contains
"java.lang.Boolean valueOf(boolean)" and the subsequent call `getMethod` can not be resolved properly and throws 

> java.lang.RuntimeException: No method java.lang.Boolean valueOf(boolean) in class java.lang.Boolean
 
which is then rethrown 

> java.lang.RuntimeException: Failed to convert <de.viadee.bpm.kglasbruch.prozess.delegate.VertragErmittelnDelegate: de.viadee.bpm.kglasbruch.webservices.fachklassen.Vertrag getVertrag(java.lang.String)>

Method: 
```
private Vertrag getVertrag(String vsnr) {
        Vertrag vertrag = null;
        return Optional.ofNullable(vertrag).orElseThrow(() -> {
            return new BpmnError("not found");
        });
}
```

I can reproduce this error using OSX and Windows, both running on JDK8. 
Is this wanted behavior and how can this be prevented? 

EDIT: Even the code snippet below throws the same error, if that helps identifying the issue.

```
private Vertrag getVertrag(String vsnr) {
        List<String> myList = Arrays.asList("element1","element2","element3");
        myList.forEach(element -> System.out.println(element));
    	return new Vertrag();
 }
```

Thanks
Sascha

**Comment by sdibernardo** [comment]
Important information: This only occurs since Soot 3.3.0. Using 3.2.0, everything seems to work fine

**Comment by sdibernardo** [comment]
I investigated a little bit deeper and observed that using Soot 3.2.0 [_findOrAdd_ ] is called (https://github.com/Sable/soot/blob/d3cff8d7dc46988570533dbf5e781eb2d115ffd2/src/main/java/soot/util/StringNumberer.java#L40)more often and adds found methods to the map

```
private Map<String, NumberedString> stringToNumbered = new HashMap<String, NumberedString>(1024);

public synchronized NumberedString findOrAdd(String s) {
    NumberedString ret = stringToNumbered.get(s);
    if (ret == null) {
      ret = new NumberedString(s);
      stringToNumbered.put(s, ret);
      add(ret);
    }
    return ret;
  }
```

In Soot 3.3.3 calls to the same method are done, but way less methods are stored inside the map. Additionally the LamdbaFactory has been introduced, which tries to resolve methods based on the primitive data types. Those were never added to the map in any prior stage, thus getting any key for a given primitive data type results in the thrown RuntimeException. 
Due to the fact that an array with the primitive data types has been initialized just a few lines prior with Boolean being the first element, this then results in the error. Changing the order would lead to the same error, with the first element being the one displayed in the throw-message.

> java.lang.RuntimeException: No method java.lang.Boolean valueOf(boolean) in class java.lang.Boolean

` PrimType[] tmp = { BooleanType.v(), ByteType.v(), CharType.v(), DoubleType.v(), FloatType.v(), IntType.v(), LongType.v(), ShortType.v() };`

As a temporary fix, adding the primitive types to the StringNumberer could avoid this error, but might result in unexpected behavior in subsequent stages. Another workaround would be to avoid resolving the primitive data types, as no other usage for the maps ([here](https://github.com/Sable/soot/blob/d3cff8d7dc46988570533dbf5e781eb2d115ffd2/src/main/java/soot/LambdaMetaFactory.java#L266)) was found by IntelliJ (might be wrong here).

``` 
private Map<RefType, PrimType> wrapperTypes;
/** valueOf(primitive) method signature */
private Map<PrimType, SootMethod> valueOf;
/** primitiveValue() method signature */
private Map<RefType, SootMethod> primitiveValue;
```

Best regards
Sascha

**Comment by TamaraGunkel** [comment]
It seems as if the methods of the basic classes are not loaded. As a workaround it might work to add the methods manually:

**Comment by TamaraGunkel** [comment]
I am working on the same project as @sdibernardo and have the same issue. 
I found that the LambdaMetaFactory requires the primitive wrapper classes to be loaded.

**Comment by mbenz89** [comment]
Hi, thanks for reporting and tracking down this issue.

I think what you actually want is phantom classes for all those primitive datatypes. Then Soot should generate the missing methods automatically.

How do you prevent Soot from loading the rt.jar? I would like to debug a bit through that behavior...

**Comment by sdibernardo** [comment]
Our current setup requires the analysis of compiled classes, so we set the Soot classpath to `..project/target/test-classes:/..project/target/classes` (censored the full path). Both folders contain the compiled jars we need to analyze. 
As options we pass 
```
Options.v().set_whole_program(true);
Options.v().set_allow_phantom_refs(true);		
```
and then 
`SootClass sootClass = Scene.v().forceResolve(className, SootClass.SIGNATURES);`

Everything up until this point works like a charm, but then loading a method and retrieving its body is where it crashes `method.retrieveActiveBody();`. If we extend Soot's classpath by adding the default classpath, then it also loads the rt.jar (which is quite unfortunate, because it bloats our analysis).

**Comment by mbenz89** [comment]
How is this related to the `LambdaMetaFactory`?

Are you checking that the method is not phantom, i.e., is able to possess a body, before calling `method.retrieveActiveBody();`?

**Comment by sdibernardo** [comment]
If the method body contains a Lambda, the method can not be loaded and a RuntimeException is thrown. It is not a phantom class :/

**Comment by mbenz89** [comment]
I see. I'm now able to reproduce the problem.

**Comment by sdibernardo** [comment]
That's good news! If there is anything we can do to help you, let us know. 👍

**Comment by mbenz89** [comment]
Should be fixed with c7b21d6a5590f1ccc1ca461568c48826e625a98b.
Can you try the [3.3.1-SNAPSHOT build](https://oss.sonatype.org/content/repositories/snapshots/ca/mcgill/sable/soot/3.3.1-SNAPSHOT/) and check if the fix works for you?

**Comment by sdibernardo** [comment]
Unfortunately I still get a RuntimeException, but this time it occurs somewhere else.
```
public void loadBasicClasses() {
        this.addReflectionTraceClasses();
        int loadedClasses = 0;

        for(int i = 3; i >= 1; --i) {
            Iterator var3 = this.basicclasses[i].iterator();

            while(var3.hasNext()) {
                String name = (String)var3.next();
                SootClass basicClass = this.tryLoadClass(name, i);
                if (basicClass != null && !basicClass.isPhantom()) {
                    ++loadedClasses;
                }
            }
        }

        if (loadedClasses == 0) {
            throw new RuntimeException("None of the basic classes could be loaded! Check your Soot class path!");
        }
    }
```
Every loaded basicClass is a phantom class, thus `!basicClass.isPhantom()` always results in false and subsequently the RuntimeException is thrown.

Thanks for the quick response!

**Comment by mbenz89** [comment]
This is the intended behavior. Note that, for example, exception handling cannot work without having a class hierarchy of exceptional classes loaded from the rt.jar.

If you are happy with that and sure that you really do not need any of the basic classes, you might want to introduce an option that prevents this check from failing. I would be happy to integrate this as a pr if properly documented in `src/main/xml/options/soot_options.xml`.

**Comment by sdibernardo** [comment]
Is it possible to properly load (no phantom class) the basic classes without loading the entire rt.jar, so the `isPhantom` check does not fail?

**Comment by mbenz89** [comment]
It is possible if you provide the required classes to Soot. Either by providing a manually shrunk rt.jar replacement jar or by directly providing the required classes.

However, if you exclude `java.*`, Soot should open the rt.jar and only load the basic classes from it anyway. Basic classes are not affected by excludes, all other classes would not be loaded. Thus, the only performance to gain with the above-mentioned hack might be due to opening a smaller jar file.

**Comment by sdibernardo** [comment]
I will try to figure out how I to deal with the given possibilities. 
Thanks 👍
